services:
  app:
    build: .
    container_name: go-app
    ports:
      - "8080:8080"
    volumes:
      - ./var/log:/app/var/log
    depends_on:
      - loki
    networks:
      - monitoring

  redis:
    image: redis:latest 
    container_name: redis
    ports:
      - "6379:6379"  
    restart: always 
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring

  loki:
    image: grafana/loki:3.4.1
    container_name: loki
    ports:
      - "3100:3100"
    command: "-config.file=/etc/loki/config.yaml"
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
      - loki-data:/tmp
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:3.4.1
    container_name: promtail
    ports:
      - "9080:9080"
    depends_on:
      - loki
    volumes:
      - ./promtail-config.yaml:/etc/prometheus/promtail-config.yaml
      - ./var/log:/var/log
    command: "-config.file=/etc/prometheus/promtail-config.yaml"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - monitoring

volumes:
  loki-data:

networks:
  monitoring:
    driver: bridge