global:
  scrape_interval: 15s  # Интервал сбора метрик

scrape_configs:
  - job_name: 'prometheus'  # Мониторинг самого Prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'  # Мониторинг сервера через Node Exporter
    static_configs:
      - targets: ['10.0.2.15:9100']  # host.docker.internal:9100
  
  - job_name: 'myapp'
    static_configs:
      - targets: ['10.0.2.15:8080']  # host.docker.internal:7540