// Code generated by MockGen. DO NOT EDIT.
// Source: recommendation_usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/probuborka/NutriAI/internal/entity"
)

// Mockai is a mock of ai interface.
type Mockai struct {
	ctrl     *gomock.Controller
	recorder *MockaiMockRecorder
}

// MockaiMockRecorder is the mock recorder for Mockai.
type MockaiMockRecorder struct {
	mock *Mockai
}

// NewMockai creates a new mock instance.
func NewMockai(ctrl *gomock.Controller) *Mockai {
	mock := &Mockai{ctrl: ctrl}
	mock.recorder = &MockaiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockai) EXPECT() *MockaiMockRecorder {
	return m.recorder
}

// Recommendation mocks base method.
func (m *Mockai) Recommendation(userNFP entity.UserNutritionAndFitnessProfile) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recommendation", userNFP)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recommendation indicates an expected call of Recommendation.
func (mr *MockaiMockRecorder) Recommendation(userNFP interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recommendation", reflect.TypeOf((*Mockai)(nil).Recommendation), userNFP)
}

// Mockcache is a mock of cache interface.
type Mockcache struct {
	ctrl     *gomock.Controller
	recorder *MockcacheMockRecorder
}

// MockcacheMockRecorder is the mock recorder for Mockcache.
type MockcacheMockRecorder struct {
	mock *Mockcache
}

// NewMockcache creates a new mock instance.
func NewMockcache(ctrl *gomock.Controller) *Mockcache {
	mock := &Mockcache{ctrl: ctrl}
	mock.recorder = &MockcacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcache) EXPECT() *MockcacheMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *Mockcache) FindByID(ctx context.Context, id string) (entity.UserNutritionAndFitnessProfileCache, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(entity.UserNutritionAndFitnessProfileCache)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockcacheMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*Mockcache)(nil).FindByID), ctx, id)
}

// Save mocks base method.
func (m *Mockcache) Save(ctx context.Context, recommendation entity.UserNutritionAndFitnessProfileCache) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, recommendation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockcacheMockRecorder) Save(ctx, recommendation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*Mockcache)(nil).Save), ctx, recommendation)
}
