// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/recommendation": {
            "get": {
                "description": "Возвращает персонализированные рекомендации по питанию и тренировкам",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Рекомендации"
                ],
                "summary": "Получить рекомендации",
                "parameters": [
                    {
                        "description": "Данные пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UserRecommendationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.RecommendationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entity.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "entity.Goals": {
            "description": "содержит цели пользователя",
            "type": "object",
            "required": [
                "primary_goal",
                "secondary_goal",
                "target_weight_kg",
                "timeframe_weeks"
            ],
            "properties": {
                "primary_goal": {
                    "type": "string",
                    "enum": [
                        "weight_loss",
                        "muscle_toning",
                        "maintenance"
                    ],
                    "example": "weight_loss"
                },
                "secondary_goal": {
                    "type": "string",
                    "enum": [
                        "weight_loss",
                        "muscle_toning",
                        "maintenance"
                    ],
                    "example": "muscle_toning"
                },
                "target_weight_kg": {
                    "type": "integer",
                    "example": 90
                },
                "timeframe_weeks": {
                    "type": "integer",
                    "example": 40
                }
            }
        },
        "entity.Lifestyle": {
            "description": "содержит информацию об образе жизни пользователя",
            "type": "object",
            "required": [
                "activity_level",
                "average_sleep_hours",
                "daily_calorie_intake",
                "workout_availability_days_per_week"
            ],
            "properties": {
                "activity_level": {
                    "type": "string",
                    "enum": [
                        "sedentary",
                        "light",
                        "moderate",
                        "active",
                        "very_active"
                    ],
                    "example": "moderate"
                },
                "average_sleep_hours": {
                    "type": "integer",
                    "example": 7
                },
                "daily_calorie_intake": {
                    "type": "integer",
                    "example": 1800
                },
                "workout_availability_days_per_week": {
                    "type": "integer",
                    "example": 4
                }
            }
        },
        "entity.MedicalRestrictions": {
            "description": "содержит медицинские ограничения пользователя",
            "type": "object",
            "required": [
                "chronic_conditions",
                "has_injuries"
            ],
            "properties": {
                "chronic_conditions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "none"
                    ]
                },
                "has_injuries": {
                    "type": "boolean",
                    "example": true
                },
                "injury_details": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "травма колена"
                    ]
                }
            }
        },
        "entity.Preferences": {
            "description": "содержит предпочтения пользователя",
            "type": "object",
            "required": [
                "allergies",
                "diet_type",
                "preferred_cuisines",
                "workout_preferences"
            ],
            "properties": {
                "allergies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "орехи",
                        "моллюски"
                    ]
                },
                "diet_type": {
                    "type": "string",
                    "enum": [
                        "vegan",
                        "keto",
                        "low_carb",
                        "balanced"
                    ],
                    "example": "balanced"
                },
                "preferred_cuisines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "средиземноморский",
                        "азиатский"
                    ]
                },
                "workout_preferences": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "силовая тренировка",
                        "кардио"
                    ]
                }
            }
        },
        "entity.Profile": {
            "description": "содержит профиль пользователя",
            "type": "object",
            "required": [
                "age",
                "fitness_level",
                "gender",
                "height_cm",
                "weight_kg"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 39
                },
                "fitness_level": {
                    "type": "string",
                    "enum": [
                        "beginner",
                        "intermediate",
                        "advanced"
                    ],
                    "example": "beginner"
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "female",
                        "male"
                    ],
                    "example": "male"
                },
                "height_cm": {
                    "type": "integer",
                    "example": 186
                },
                "weight_kg": {
                    "type": "integer",
                    "example": 140
                }
            }
        },
        "entity.RecommendationResponse": {
            "type": "object",
            "properties": {
                "recommendations": {
                    "type": "string"
                }
            }
        },
        "entity.RequestDetails": {
            "description": "содержит детали запроса",
            "type": "object",
            "required": [
                "language",
                "output_format",
                "service_type"
            ],
            "properties": {
                "language": {
                    "type": "string",
                    "enum": [
                        "ru",
                        "en"
                    ],
                    "example": "ru"
                },
                "output_format": {
                    "type": "string",
                    "enum": [
                        "daily_plan",
                        "weekly_plan",
                        "general_advice"
                    ],
                    "example": "weekly_plan"
                },
                "service_type": {
                    "type": "string",
                    "enum": [
                        "fitness_nutrition_recommendations"
                    ],
                    "example": "fitness_nutrition_recommendations"
                }
            }
        },
        "entity.UserData": {
            "description": "содержит данные пользователя",
            "type": "object",
            "required": [
                "goals",
                "lifestyle",
                "medical_restrictions",
                "preferences",
                "profile"
            ],
            "properties": {
                "goals": {
                    "$ref": "#/definitions/entity.Goals"
                },
                "lifestyle": {
                    "$ref": "#/definitions/entity.Lifestyle"
                },
                "medical_restrictions": {
                    "$ref": "#/definitions/entity.MedicalRestrictions"
                },
                "preferences": {
                    "$ref": "#/definitions/entity.Preferences"
                },
                "profile": {
                    "$ref": "#/definitions/entity.Profile"
                }
            }
        },
        "entity.UserRecommendationRequest": {
            "description": "Информация о пользователе",
            "type": "object",
            "required": [
                "request_details",
                "user_data",
                "user_id",
                "user_name"
            ],
            "properties": {
                "recommendations": {
                    "type": "string"
                },
                "request_details": {
                    "$ref": "#/definitions/entity.RequestDetails"
                },
                "user_data": {
                    "$ref": "#/definitions/entity.UserData"
                },
                "user_id": {
                    "type": "string",
                    "example": "123456789"
                },
                "user_name": {
                    "type": "string",
                    "example": "Евгений"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "NutriAI",
	Description:      "Микросервис предоставляет пользователям персонализированные рекомендации по питанию и тренировкам.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	// LeftDelim:        "{{",
	// RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
